### ISSUE TITLE
Make file is not complete

### ISSUE THREAD

**Issue by kirson-git** [NVIDIA/k8s-nim-operator#169]
The following are not included within the make file

make docker-build 
docker-push 

kirson@nim-airgapped:/tmp/k8s-nim-operator$ make docker-build docker-push IMG=harbor.runailabs-ps.com/guest-repo/kirson-nim:1.0
make: *** No rule to make target 'docker-build'.  Stop.

**Comment by shivamerla** [comment]
Fixing the Readme. Please run `make build -f deployments/container/Makefile`

**Comment by shivamerla** [comment]
Closing this, please re-open if you see other issues.
