### ISSUE TITLE
nim service : service type didnt reflect to svc

### ISSUE THREAD

**Issue by jxdn** [NVIDIA/k8s-nim-operator#178]
apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: meta-llama3-8b-instruct
  namespace: nim
spec:
  image:
    repository: nvcr.io/nim/meta/llama3-8b-instruct
    tag: 1.0.3
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  storage:
    nimCache:
      name: meta-llama3-8b-instruct
      profile: ''
  replicas: 2
  resources:
    limits:
      nvidia.com/gpu: 1
  expose:
    service:
      type: LoadBalancer
      port: 8000

but it didnt reflect to our svc

![Image](https://github.com/user-attachments/assets/2689fdc4-1b7c-4e45-a697-1097eabc28b0)

**Comment by mkhaas** [comment]
Can you share details on where you are running it? describe the NIMService and loadbalancers available? thanks

**Comment by jxdn** [comment]
iam runing on k3s ... load balancer using nginx class

**Comment by shivamerla** [comment]
Fixed with https://github.com/NVIDIA/k8s-nim-operator/pull/193
