### ISSUE TITLE
CRD nimcache miss

### ISSUE THREAD

**Issue by iming0319** [NVIDIA/k8s-nim-operator#179]
file: deployments/helm/k8s-nim-operator/crds/apps.nvidia.com_nimcaches.yaml
spec.resources 
Resources defines the minimum resources required for the caching job to run(cpu, memory, gpu).
it missed a property "gpus"
now GPUs CANNOT specifies the number of GPUs to assign to the caching job.

reference link: [https://github.com/NVIDIA/k8s-nim-operator/blob/f678cd641c423c06425afe3f7647bd28213f4690/deployments/helm/k8s-nim-operator/crds/apps.nvidia.com_nimcaches.yaml#L70](url)

**Comment by shivamerla** [comment]
@iming0319 we don't need to assign GPUs for caching job? Can you provide the use case?

**Comment by iming0319** [comment]
I think this is because of the version gap.
I'll study the new CRD
