### ISSUE TITLE
nim cache: issue on megatron 1b profiles

### ISSUE THREAD

**Issue by jxdn** [NVIDIA/k8s-nim-operator#182]
`apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: megatron-1b
  namespace: nim
spec:
  source:
    ngc:
      modelPuller: nvcr.io/nim/nvidia/megatron-1b-nmt:1.0.0
      pullSecret: ngc-secret
      authSecret: ngc-api-secret
      model:
        engine: tensorrt_llm
        tensorParallelism: "1"
  storage:
    pvc:
      create: true
      size: "50Gi"
      storageClass: "storage-nvme-c1"
      volumeAccessMode: ReadWriteMany
  resources: {}`

when i describe the nim cache 

![Image](https://github.com/user-attachments/assets/534407c5-be39-468c-a050-f06fdb3d2ef3)

**Comment by jxdn** [comment]
happened with asr, tts models also

**Comment by shivamerla** [comment]
@jxdn RIVA NIMs are not yet supported with the operator. We plan to add these in the upcoming release.

**Comment by jxdn** [comment]
thanks
